[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

[FILTER]
    Name          rewrite_tag
    Match         kube.*
    Rule          $log "(?i)(password|token|secret|media_key)" sanitized.security false

[FILTER]
    Name          modify
    Match         sanitized.security
    Condition     Key_Value_Matches log (?i)(bearer\s+[a-z0-9\-_\.]+)
    Set           log [REDACTED_SECURITY_DATA]

[OUTPUT]
    Name          loki
    Match         *
    Host          loki.monitoring.svc.cluster.local
    Port          3100
    Labels        job=fluent-bit
