/* Auto-generated by cbindgen. Do not edit. */

/* Generated with cbindgen:0.27.0 */

/* WARNING: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by FFI functions
 */
#define GenChatGENCHAT_OK 0

#define GenChatGENCHAT_ERR_NULL_PTR -1

#define GenChatGENCHAT_ERR_INVALID_ARG -2

#define GenChatGENCHAT_ERR_CRYPTO -3

#define GenChatGENCHAT_ERR_ALLOC -4

/**
 * C-compatible pre-key bundle for PQXDH
 */
typedef struct GenChatCPreKeyBundle {
  uint8_t identity_key[32];
  uint8_t identity_key_x25519[32];
  uint32_t signed_pre_key_id;
  uint8_t signed_pre_key[32];
  uint8_t signed_pre_key_sig[64];
  uint32_t pq_pre_key_id;
  const uint8_t *pq_pre_key;
  size_t pq_pre_key_len;
  uint8_t pq_pre_key_sig[64];
  int has_one_time_key;
  uint32_t one_time_key_id;
  uint8_t one_time_key[32];
} GenChatCPreKeyBundle;

/**
 * C-compatible PQXDH init message output
 */
typedef struct GenChatCInitMessage {
  uint8_t sender_identity_key[32];
  uint8_t sender_identity_key_x25519[32];
  uint8_t ephemeral_key[32];
  uint8_t *pq_ciphertext;
  size_t pq_ciphertext_len;
  uint32_t used_signed_pre_key_id;
  uint32_t used_pq_pre_key_id;
  int has_one_time_key_id;
  uint32_t used_one_time_key_id;
} GenChatCInitMessage;

/**
 * Generate a new Ed25519 identity keypair.
 */
GenChatIdentityKeyPair *genchat_identity_keypair_generate(void);

/**
 * Copy the 32-byte public key into the provided buffer.
 */
int genchat_identity_keypair_public_key(const GenChatIdentityKeyPair *kp, uint8_t *out);

/**
 * Sign a message, writing the 64-byte signature to the output buffer.
 */
int genchat_identity_keypair_sign(const GenChatIdentityKeyPair *kp,
                                  const uint8_t *msg,
                                  size_t msgLen,
                                  uint8_t *outSig);

/**
 * Free an identity keypair.
 */
void genchat_identity_keypair_free(GenChatIdentityKeyPair *kp);

GenChatX25519KeyPair *genchat_x25519_keypair_generate(void);

int genchat_x25519_keypair_public_key(const GenChatX25519KeyPair *kp, uint8_t *out);

void genchat_x25519_keypair_free(GenChatX25519KeyPair *kp);

GenChatPqKeyPair *genchat_pq_keypair_generate(void);

int genchat_pq_keypair_encapsulation_key(const GenChatPqKeyPair *kp, uint8_t *out, size_t *outLen);

void genchat_pq_keypair_free(GenChatPqKeyPair *kp);

GenChatGenChatAccount *genchat_account_new(void);

int genchat_account_generate_one_time_keys(GenChatGenChatAccount *account, size_t count);

void genchat_account_free(GenChatGenChatAccount *account);

/**
 * Encrypt plaintext, allocating output buffer.
 * Caller must free the output using genchat_free.
 */
int genchat_session_encrypt(GenChatGenChatSession *session,
                            const uint8_t *plaintext,
                            size_t plaintextLen,
                            uint8_t **outCiphertext,
                            size_t *outLen,
                            uint8_t *outMsgType);

/**
 * Decrypt ciphertext, allocating output buffer.
 * Caller must free the output using genchat_free.
 */
int genchat_session_decrypt(GenChatGenChatSession *session,
                            uint8_t msgType,
                            const uint8_t *ciphertext,
                            size_t ciphertextLen,
                            uint8_t **outPlaintext,
                            size_t *outLen);

void genchat_session_free(GenChatGenChatSession *session);

/**
 * Create a new MLS group with creator as first member.
 */
GenChatMlsGroup *genchat_mls_group_create(const char *groupId,
                                          const char *userId,
                                          const char *deviceId,
                                          const GenChatIdentityKeyPair *identity,
                                          const GenChatX25519KeyPair *hpkeKp);

/**
 * Encrypt an application message for an MLS group.
 */
int genchat_mls_group_encrypt(GenChatMlsGroup *group,
                              const uint8_t *plaintext,
                              size_t plaintextLen,
                              uint8_t **outCiphertext,
                              size_t *outLen);

/**
 * Decrypt an MLS group message.
 */
int genchat_mls_group_decrypt(const GenChatMlsGroup *group,
                              const uint8_t *ciphertextJson,
                              size_t ciphertextLen,
                              uint8_t **outPlaintext,
                              size_t *outLen);

/**
 * Free an MLS group state.
 */
void genchat_mls_group_free(GenChatMlsGroup *group);

/**
 * Free memory allocated by genchat FFI functions.
 */
void genchat_free(uint8_t *ptr, size_t len);
